# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title
markdown: kramdown

# highlighter: pygments
paginate: 20 # pagination based on number of posts
paginate_path: "page/:num"

categories_path : categories.html
tags_path : tags.html

BASE_PATH : ""

title : PrasunPK

author:
  name: Prasun
  role: Application Developer
  email: "--"
  github: prasunpk
  twitter: iam_prasun
  facebook: prasun.kumarpalchowdhury
  googleplus: +prasun
  bio: "Simple thoughts to express ... "
  avatar: avatar.png


gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
